list1=[]

lst= ["Games Designer", "Software Developer ", "Game Programmer", "Audio Engineer", "Games Animator", "Games Artist",
      "Interpreters and Translators", "Game Play Tester", "Professional Gamer", "Marketing Managers", "Market Research Analysts",
      "Writer", "Project Manager", "Graphics Engineer" ]

print(' We are Hiring, \n  Enter the job position you are applying for')
for i in lst:
    print(i)

input1 = str(input("write down your job position here \n "))
if input1==lst[0]:
    print(f" Game Designer Job Description \n  We are seeking out a recreation clothier with a ardour for all genres of video games, a knack for coding and storytelling, and an expertise of the enterprise, marketplace and goal audiences. Game designers can count on to manipulate groups of programmers, artists, animators and sound engineers, in addition to plan schedules and paintings with budgets. Their duties additionally encompass growing layout and gaming protocols, defining recreation-play mechanics, coordinating with different recreation designers, making sure nice, and assembly with enterprise executives. To be a a success recreation clothier, you have to have terrific coding skills, no troubles with operating lengthy hours beneathneath pressure, a longing for making video games which can be authentic and groundbreaking, and a love for the process. Ideal applicants could have revel in in recreation layout, information of pc structures and languages, exceptional verbal exchange and collaboration skills. \n  Game Designer Responsibilities: \n  Creating revolutionary video games for leisure or schooling purposes. Conceptualizing and growing characters, rules, settings and memories for brand new video games. Pitching new recreation thoughts to executives and clients. Managing a couple of groups and projects. Prototyping new video games. Following enterprise developments and properly practices. Monitoring paintings and coins flows. Developing layout and gaming protocols. Doing nice control. Game Designer Requirements: Bachelor's diploma in recreation layout, pc technology or pc engineering. Enthusiasm and information of the enterprise. Relevant certification in programming languages. Portfolio of pattern projects.  {input1}")

elif input1==lst[1]:
    print(f" Software Developer Job Description: \n Our corporation is searching for to lease a professional software program developer to assist with the improvement of our cutting-edge projects. Your responsibilities will in the main revolve round constructing software program with the aid of using writing code, in addition to editing software program to repair errors, adapt it to new hardware, enhance its overall performance, or improve interfaces. You may also be concerned in directing device checking out and validation procedures, and additionally operating with clients or departments on technical problems inclusive of software program device layout and maintenance. To achieve success on this role, you'll want sizeable understanding of programming languages and the software program improvement life-cycle. A bachelor's diploma in laptop technology or associated diploma is required. Software Developer Responsibilities: \n  Modifying software program to repair errors, adapt it to new hardware, enhance its overall performance, or improve interfaces. Directing device checking out and validation procedures. Directing software program programming and documentation improvement. Consulting with departments or clients on venture repute and proposals. Working with clients or departments on technical problems inclusive of software program device layout and maintenance. Analyzing records to suggest and plan the set up of latest structures or changes of an current device. Consulting with engineering personnel to assess software program hardware interfaces and increase specs and overall performance requirements. Designing and growing software program structures the usage of medical evaluation and mathematical fashions to are expecting and degree results and layout consequences. Preparing reviews on programming venture specs, activities, or repute. Conferring with venture managers to attain records on barriers or capabilities. Software Developer Requirements: Bachelor's diploma in laptop technology or associated diploma. Knowledge of the software program improvement life-cycle. The preference to paintings in a fast paced environment. Ability to increase unit checking out of code additives or entire applications. Creativity is constantly a plus. Must be a full-stack developer and apprehend ideas of software program engineering. Experience operating on quite a few software program improvement projects. Deep programming language understanding.  {input1}")

elif input1==lst[2]:
    print(f" Game Programmer Job Description: \n  We are seeking out a results-orientated recreation programmer to sign up for our recreation layout team. You might be brainstorming recreation principles with the layout team, growing video games via way of means of the use of appropriate programming languages, and acting code maintenance. To make sure achievement as a recreation programmer, you have to show vast understanding of programming languages and their programs and revel in in a comparable role. An wonderful recreation programmer might be a person whose knowledge interprets into trendsetting reviews for recreation enthusiasts. \n  Brainstorming recreation principles, layout elements, and specs with the sport layout team. Collaborating with programmers to set paintings schedules and deadlines. Selecting appropriate recreation frameworks and translating principles into smooth and green code. Designing and checking out gameplay capabilities and prototypes. Generating recreation scripts and storyboards, in addition to animating recreation characters and objects. Contributing to consumer interface improvement, in addition to the mixing of photograph layout and audio capabilities. Performing checks and imposing validation procedures. Documenting the whole lifecycle of recreation improvement. Maintaining code, resolving issues, and acting computer virus fixes. Integrating the trendy recreation enterprise traits into recreation designs. Game Programmer Requirements: Bachelor's diploma in laptop science, laptop engineering, or comparable. Coursework or certification in recreation layout and improvement preferred. At least 2 years of revel in as a recreation programmer. In-intensity understanding of complete lifecycle recreation programming and associated technologies. Highly gifted in programming languages, which include C++ and Java. Superb analytical and problem-fixing skills. Excellent verbal exchange and collaboration abilities. Great organizational and time control skills. Ability to make a contribution to innovation in recreation layout.     {input1}")

elif input1 == lst[3]:
    print(f" Audio Engineer Job Description: \n  We are attempting to find a reliable, detail-oriented audio engineer to sign up for our developing team. The audio engineer’s duties consist of growing and modifying recordings, putting in gadget in studio and at events, following patron specifications, and assembly challenge closing dates. You need to have exceptional time control and display up on agenda for studio periods and stay gigs. To achieve success as an audio engineer, you need to have a discerning ear and be capable of perceive what sounds good. Outstanding applicants are informed approximately audio gadget, capable of comply with written and verbal instructions, and always supply high-quality results.  \n  Audio Engineer Responsibilities: \n  Understanding patron briefs and choosing the correct sound and combining gadget for the challenge. Communicating with customers and coordinating with different body of workers contributors to make certain closing dates are met and tasks are finished to specifications. Editing, mixing, and manipulating recorded and stay sound. Setting up gadget competently and on time. Designing audio structures and advising customers on gadget purchases. Testing and troubleshooting gadget regularly, and changing any defective components. Fixing and improving sound at stay events. Collaborating and networking with different Audio Engineers and specialists withinside the field. Participating in schooling possibilities and continuously locating new approaches to enhance skills. Audio Engineer Requirements: High college diploma. Certificate in audio era or comparable recommended. Practical enjoy with sound gadget. Superb ear for sound. Ability to paintings beneathneath stress and live calm while matters cross wrong. Excellent customer support and interpersonal skills. Professional self-starter with a boom mindset.    {input1}")

elif input1==lst[4]:
    print(f" Game Animator Job Description: \n  We are seeking to rent a innovative sport animator to enroll in our online game manufacturing crew. As the sport animator, it is going to be your obligation to studies, layout, and increase top-high-satisfactory animations for numerous sport genres. You'll additionally be predicted to paintings along the artwork branch to make sure that each one visible art work meets clients' specifications. To excel on this position, you need to be element-oriented, inventive, and feature in-intensity know-how of online game animation era and software program. Ultimately, a top-notch sport animator need to be a crew participant it is capable of reveal outstanding verbal exchange and interpersonal skills. \n  Game Animator Responsibilities:  \n  Researching online game animation trends, techniques, and statistics. Designing and generating top-high-satisfactory animations that meet our employer's preferred. Collaborating with programmers and builders to make sure that each one layout briefs are adhered to. Using pc software program and hardware structures to create interactive animations and unique effects. Presenting thoughts and studies findings to control and capability investors. Compiling layout briefs and reviews that element the necessities wanted to finish an order. Representing our employer at online game showcases, presentations, and exhibitions. Outlining long-time period goals for unique tasks that exceed preferred online game manufacturing time. Game Animator Requirements: Bachelor's diploma in pc artwork and/or animation. A minimal of two years of enjoy as a sport animator. A complete virtual portfolio of finished tasks. Experience in modeling, rigging, and skinning fashions for video games. Good know-how of online game improvement and the artwork-introduction process. Strong draw close of Photoshop, Maya, and 3ds Max. Exceptional verbal exchange and teamwork skills. A innovative eye for artwork course and online game unique effects.    {input1}")

elif input1==lst[5]:
    print(f" Game Artist task description: \n  Game Artist task description need to begin with an interesting, attractive creation. Here is an concept of what this creation may also appearance like: We are increasing our group and seeking out a innovative and energetic, Senior Game Artist to sign up for us. In this function you may create compelling, emotionally impactful paintings that suits and complements the set up fashion and branding of our computer and cell platform. We have a fast-paced, collaborative surroundings in which you may paintings with artwork directors, recreation designers, manufacturers and programmers withinside the advent and implementation of main side video games and features. Game Artist task description: Job responsibilities and responsibilities Game Artist task description need to comprise the subsequent responsibilities and \n responsibilities: \n  To layout and illustrate for video games, consisting of Slots, Bingo and Casino Ability to push innovative initiatives from idea to very last execution Collaborating with the group at the execution of each massive and small initiatives with the equal enthusiasm Maintaining current merchandise and supplying belongings for advertising purposes Ability to speak nicely with one-of-a-kind humans even beneathneath pressure Be passionate, prompted and enthusiastic about what you do! Work for the coolest of the group and exellence of the product Game Artist task description: Job necessities and qualifications Game Artist task description need to comprise the subsequent necessities and qualifications: Online gaming experience Games UI experience Game emblem advent Shot composition and framing Digital painting Photoshop Illustrator Flash Digital Illustration.   {input1}")

elif input1==lst[6]:
    print(f" Interpreter Job Description: \n  We are searching out a in a position Interpreter to offer help to non-English audio system throughout a number of activities. The interpreter will offer interpretation offerings for the duration of diverse processes, and make sight translations of files. You will offer correct standards and factors with out a additions or omissions, and in keeping with conventions of installed interpretation protocol. You will perceive elements that avert your overall performance as an Interpreter, and rapidly record those to applicable events. To make sure achievement you want to manner and impart records rapidly, and relay intentions, feelings and tone to your interpretations. Preferred candidates have brilliant problem-fixing skills, and feature the capacity to paintings to a excessive stage of accuracy. \n  Interpreter Responsibilities: \n   Acting as Interpreter among a extensive variety of human beings with various voices, accents, speakme tempos and personalities. Providing events with clean and genuine translations of written materials, and interpretations of verbal communique. Providing interpretations of questions, answers, statements, arguments, factors and different kinds of verbal communique. Rendering sight translations of files and different written materials. Imparting thought, purpose, spirit, feelings and tone of audio system from supply language into goal language. Interpreting with out a additions or omissions. Informing applicable events of things which could avert your overall performance. Completion of day by day interest logs and different documentation. Complying with relevant ethics and standards. Interpreter Requirements: High faculty diploma, GED, or appropriate equivalent. Valid certificates of accepted deciphering training. Excellent bilingual communique skills, each verbal and written. Valid driver’s license. Proficient pc skills. Proficient with use of workplace equipment. Outstanding listening, retention and note-taking skills. Proficient enunciation and pronunciation skills, and pleasant, expert voice. Proficient expertise of cultural sensitivity, and capacity to collaborate with human beings from various cultural backgrounds.     {input1}")

elif input1==lst[7]:
    print(f" Game Tester Job Description:  \n  We are searching out an skilled online game tester to check and assessment our video games earlier than they exit to market. In this position you may be required to play each recreation to competition, noting any insects or system faults at the way. You may also be required to play each level, discover hidden objects, and endorse any extensions or modifications. To make certain fulfillment as a online game tester, you must have in-intensity understanding of online game design, a ardour for gaming, and a terrific eye for detail. A top-notch online game tester is familiar with the psychology of a gamer and notes any information that might impede the income overall performance of the product. \n  Video Game Tester Responsibilities:  \n  Playing the sport to completion. Completing all aspect quests and exploring all levels. Finding and exploring places now no longer expected through the sport designers. Making a be aware of all system faults and insects in the sport. Collecting all XP factors and leveling up characters. Achieving the very best man or woman level. Playing with special characters. Communicating any troubles to the sport designers. Recommending recreation additions or modifications. Rating the sport in phrases of entertainment and difficulty. Video Game Tester Requirements: Bachelor’s diploma in laptop science. Previous revel in as a online game tester. Passion for gaming. Advanced laptop skills. Experience with PC, console, and cell video games. Advanced knowledge of recreation dynamics, sandbox explorations, aspect quests, and hidden levels. Attention to detail. Good conversation skills. Ability to consciousness for lengthy periods. Patience and persistence.     {input1}")

elif input1==lst[8]:
    print(f" Professional Gamer Job Description: \n  Professional game enthusiasts play video video games in competitions or for audiences. The opposition set makes cash from agreement charges that proprietors or traders pay to have them on their team. They make cash while their groups win, and additionally from sponsorship via way of means of important companies, inclusive of Intel or Coca-Cola. For seasoned game enthusiasts who stay movement their gameplay on Twitch, there's advert sales and subscription sales to be had. Some might also additionally even promote their very own merchandise, or they'll receive payoffs to check or sell a selected product in the course of their movement. The existence of a seasoned gamer isn't always all a laugh and video games, though. Many expert online game gamers exercise for up to 8 hours in keeping with day.  \n  Requirements: \n   Pro game enthusiasts do now no longer want a proper education, simply a variety of exercise. Many specialize in only one online game, inclusive of Dota 2; League of Legends; Overwatch; PlayerUnknown's Battlegrounds; or StarCraft II. These gamers exercise, then watch replays in their very own recreation play so they can examine the strategies. They watch streams of different gamers, so they can research their fashion and to discern out the way to make the most their weaknesses in tournament. As gamers from the seasoned gaming world, they'll discover themselves fascinated in, to various degrees, in recreation layout, recreation programming and development, or in image layout and recreation art.   {input1}")

elif input1==lst[9]:
    print(f" Marketing Manager covers a enormous spectrum of obligations inside a enterprise, from the merchandising of services and products proper the manner via to analysing information and putting method for a way a business enterprise goes to grow. Because advertising may have a profound impact on each detail of a business enterprise and the manner it operates, advertising control is a totally accountable position. Primarily the advertising branch exists to discover new methods of producing sales and clients aligned with the fast-transferring tempo of era, in addition to optimising and modernising conventional advertising methods. A innovative thoughts and a head for enterprise are critical to be successful withinside the position of a advertising manager. Strong communique coupled with the capacity to guide and encourage a crew are taken into consideration middle capabilities for this position. Marketing control is an to be had and available profession course for each person at any degree of their profession, and salaries for advertising managers are generous. For the ones looking for to development quickly, senior advertising possibilities are plentiful, with wages and blessings growing with enjoy and stage of responsibility. Most importantly, advertising control is a amusing profession choice; it may provide the ability to travel, cope with luxurious items and services, attend massive events, or even participate in new era trials. Discover insights and recommendation from specialists who're presently doing the job. Here, we’ll delve into the info of the position, the capabilities and qualifications you’ll need, and discover advertising control careers. {input1}")

elif input1==lst[10]:
    print(f" Market Research Analyst Job Description: \n  We are seeking to rent a marketplace studies analyst with high-quality organizational and studies capabilities. Market studies analysts are predicted to be targeted people with a sturdy skillability in math and sound commercial enterprise acumen. To make certain success, marketplace studies analysts need to be terrific communicators and intuitively understand styles with a eager hobby in presenting useful and correct perception into customer conduct and competition’ techniques. Top applicants will showcase important wondering capabilities, sturdy IT capabilities and an intensive interest to detail. \n  Market Research Analyst Responsibilities: \n  Monitor and forecast advertising and marketing and income trends. Assist withinside the improvement of advertising and marketing plans. Conduct studies on unique marketplace conditions. Analyze customer possibilities to decide the ability income of a product or service. Analyze prices, strategies of advertising and marketing and distribution. Measure the effectiveness of advertising and marketing packages and techniques. Devise and compare strategies for facts collection. Gather facts on consumers, competition and marketplace conditions. Use statistical software program to research and interpret facts. Maintain strict confidentiality of touchy records. Simplify complicated facts right into a user-pleasant layout including graphs, charts and different visible aids. Prepare and gift reviews to customers and management. Market Research Analyst Requirements: Bachelors diploma in marketplace studies or related (essential). Two years of enjoy in marketplace studies and analysis. Analytical philosopher with sturdy theoretical and studies proficiencies. Ability to recognize and interpret competitor techniques and customer conduct. Thorough expertise of advertising and marketing packages and techniques. Ability to accumulate huge quantities of facts and convert it into significant analysis. Solid organizational capabilities and detail-oriented. Ability to paintings beneathneath stress and meet strict deadlines. Strong skillability in math, net analytics and commercial enterprise studies tools. Brilliant written and verbal communique capabilities. Ability to simplify complicated records right into a user-pleasant layout. Proficient in Microsoft Office, databases and statistical packages.  {input1}")

elif input1==lst[11]:
    print(f" Writer Job Description: \n We are seeking to rent a committed content material creator to create content material for blogs, articles, product descriptions, social media, and the employer website. The content material creator's duties encompass comparing analytics to modify content material as needed, frequently updating the employer's website, and selling the employer weblog with the aid of using pitching articles to numerous third-celebration platforms. You need to additionally be capable of comply with editorial suggestions while growing content material. To achieve success as a content material creator, you need to hold abreast of the today's search engine marketing techniques. Ultimately, a top-appearing Content Writer need to be capable of make a contribution to the improvement of techniques to be able to boom reader engagement. \n Writer Responsibilities: \n   Conducting in-intensity studies on industry-associated subjects with a view to expand authentic content material. Developing content material for blogs, articles, product descriptions, social media, and the employer website. Assisting the advertising group in growing content material for marketing and marketing campaigns. Proofreading content material for mistakes and inconsistencies. Editing and sprucing current content material to enhance readability. Conducting key-word studies and the use of search engine marketing first-class practices to boom visitors to the employer website. Creating compelling headlines and frame replica to be able to seize the eye of the goal audience. Identifying customers’ desires and recommending new content material to deal with gaps withinside the employer's present day content material. Content Writer Requirements: Bachelor's diploma in communications, advertising, english, journalism, or associated field. Proven content material writing or copywriting experience. Working understanding of content material control systems. Proficient in all Microsoft Office applications. A portfolio of posted articles. Excellent writing and modifying skills. The capacity to paintings in a fast moving environment. The capacity to deal with a couple of tasks concurrently. Effective communique skills.    {input1}")

elif input1==lst[12]:
    print(f"  Project Manager Job Description: \n We are seeking out a task supervisor to be chargeable for coping with our company's ongoing tasks. You can be running intently together along with your crew individuals to make sure that each one task requirements, deadlines, and schedules are on the right track. Responsibilities encompass filing task deliverables, making ready repute reviews, and organising powerful task communique plans in addition to the right execution of stated plans. To be a a hit candidate, you'll want to have established revel in in task control and the capacity to guide task groups of numerous sizes. A Project Management Professional (PMP) certification is a large advantage. \n Project Manager Responsibilities: \n Coordinating with cross-area crew individuals to make certain that each one events are on the right track with task requirements, deadlines, and schedules. Meeting with task crew individuals to perceive and remedy issues. Submitting task deliverables and making sure that they adhere to exceptional standards. Preparing repute reviews via way of means of gathering, analyzing, and summarizing applicable information. Establishing powerful task communique plans and making sure their execution. Facilitating alternate requests to make sure that each one events are knowledgeable of the affects on agenda and budget. Coordinating the improvement of consumer manuals, education materials, and different files as had to allow a hit implementation and turnover of the technique or machine to the clients. Identifying and growing new possibilities with clients. Obtaining client popularity of task deliverables. Managing client pleasure inside the task transition period. Conducting post-task assessment and figuring out a hit and unsuccessful task elements. ERP task oversight. Project Manager Requirements: A bachelor’s diploma or master's diploma in a associated field. Project Management Professional (PMP) certification is a plus. Proven revel in in task control. Ability to guide task groups of numerous sizes and spot them thru to completion. Strong know-how of formal task control methodologies. Experience as a production task supervisor, IT task supervisor, or ERP task supervisor. Able to finish tasks in a well timed manner. Understanding of ERP implementation. Experience overseeing a production task. Budget control revel in.      {input1}")

elif input1==lst[13]:
    print(f" Graphics engineers create incorporated pix and visible outcomes structures which are used withinside the layout and improvement of software program applications, inclusive of video video games and working structures. In phrases of occupational focus, they're maximum intently related to pc hardware engineers and software program developers. In particular, pix engineers write code in diverse programming languages to create a visible consumer interface for structures software program or end-consumer programs. They might also talk over with artwork directors, picture designers and different associated specialists to offer them with the pc equipment and software program they want to provide movement pix and visuals. {input1}")


else:
    print('Please enter a valid input')






HiringJobDescription

This is a project hiring job positions and their requirments